/**
 * Constants for Adquimo React SDK
 */

export const ADQUIMO_CONSTANTS = {
  VERSION: '1.0.0',
  API_VERSION: 'v1',
  DEFAULT_BASE_URL: 'https://api.adquimo.com',
  DEFAULT_BATCH_SIZE: 50,
  DEFAULT_FLUSH_INTERVAL: 10000, // 10 seconds
  DEFAULT_RETRY_ATTEMPTS: 3,
  DEFAULT_RETRY_DELAY: 1000, // 1 second
  MAX_EVENT_PROPERTIES: 100,
  MAX_USER_PROPERTIES: 50,
  MAX_SESSION_PROPERTIES: 25,
  STORAGE_KEYS: {
    USER_ID: 'adquimo_user_id',
    SESSION_ID: 'adquimo_session_id',
    EVENTS: 'adquimo_events',
    USER_PROPERTIES: 'adquimo_user_properties',
    SESSION_PROPERTIES: 'adquimo_session_properties',
  },
  EVENT_TYPES: {
    PAGE_VIEW: 'page_view',
    CLICK: 'click',
    CUSTOM: 'custom',
    SESSION_START: 'session_start',
    SESSION_END: 'session_end',
    USER_IDENTIFY: 'user_identify',
    USER_ALIAS: 'user_alias',
    USER_RESET: 'user_reset',
  },
  ERROR_CODES: {
    INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
    SDK_NOT_INITIALIZED: 'SDK_NOT_INITIALIZED',
    TRACKING_ERROR: 'TRACKING_ERROR',
    PAGE_VIEW_ERROR: 'PAGE_VIEW_ERROR',
    CLICK_ERROR: 'CLICK_ERROR',
    USER_IDENTIFICATION_ERROR: 'USER_IDENTIFICATION_ERROR',
    USER_ALIAS_ERROR: 'USER_ALIAS_ERROR',
    RESET_ERROR: 'RESET_ERROR',
    ANALYTICS_ERROR: 'ANALYTICS_ERROR',
    FLUSH_ERROR: 'FLUSH_ERROR',
    DESTROY_ERROR: 'DESTROY_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    STORAGE_ERROR: 'STORAGE_ERROR',
  },
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
  },
  SESSION_TIMEOUT: 30 * 60 * 1000, // 30 minutes
  MAX_EVENT_QUEUE_SIZE: 1000,
  DEFAULT_DEBOUNCE_DELAY: 0,
  DEFAULT_SCROLL_THRESHOLD: 50,
} as const;

export type AdquimoEventType = typeof ADQUIMO_CONSTANTS.EVENT_TYPES[keyof typeof ADQUIMO_CONSTANTS.EVENT_TYPES];
export type AdquimoErrorCode = typeof ADQUIMO_CONSTANTS.ERROR_CODES[keyof typeof ADQUIMO_CONSTANTS.ERROR_CODES];
